name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    name: 'Linting backend CI'
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run lint
        run: pipenv run lint
        working-directory: starter/backend

  test:
    name: 'Testing backend CI'
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run test
        run: pipenv run test
        working-directory: starter/backend

  build:
    name: 'Building backend CI'
    needs: [ lint, test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv install
        working-directory: starter/backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          cd starter/backend
          docker build --no-cache --tag mp-backend:latest .

      - name: Run docker image
        run: docker run -p 5001:5001 --name mp-backend -d mp-backend

      - name: Check the running application
        run: curl http://localhost:5001/movies

      - name: Review logs
        run: docker logs mp-backend